#!/bin/bash


#NOTE: for this script to work bbb-poll-install must be in the polling-module directory. Please do not move it.

# BBB - CHANGE TO YOUR BIGBLUEBUTTON DIRECTORY
BBB=/home/firstuser/dev/source/bigbluebutton


################################################
if [ -d $BBB ]
then
echo " #####################################################################"
echo " "
echo "Copying polling recorder to bbb-aps ......"

  mkdir -p $BBB/bigbluebutton-apps/src/main/java/org/bigbluebutton/conference/service/recorder/polling

  if [ -d $BBB/bigbluebutton-apps/src/main/java/org/bigbluebutton/conference/service/recorder/polling ] #if polling directory exist copy files
   	 then
            	cp  ./bbb-aps/src.main.java.bigbluebutton.conference.service.recorder/polling/PollInvoker.java  $BBB/bigbluebutton-apps/src/main/java/org/bigbluebutton/conference/service/recorder/polling/PollInvoker.java
		cp  ./bbb-aps/src.main.java.bigbluebutton.conference.service.recorder/polling/PollRecorder.java  $BBB/bigbluebutton-apps/src/main/java/org/bigbluebutton/conference/service/recorder/polling/PollRecorder.java

             if [ -f  $BBB/bigbluebutton-apps/src/main/java/org/bigbluebutton/conference/service/recorder/polling/PollInvoker.java ] &&
		[ -f  $BBB/bigbluebutton-apps/src/main/java/org/bigbluebutton/conference/service/recorder/polling/PollRecorder.java ]
               then
	    		echo "                                                             [Done]"
              fi
	
    	else
        	  echo "Error Copying Server Side components. make sure you use 'sudo ./bbb-poll-install '"
        	  exit
	fi   
###################################################

        echo "Copying  poll module  to bbb-aps ......"


	mkdir -p $BBB/bigbluebutton-apps/src/main/java/org/bigbluebutton/conference/service/poll
	if [ -d $BBB/bigbluebutton-apps/src/main/java/org/bigbluebutton/conference/service/poll ]
  	 then
         	cp   ./bbb-aps/src.main.java.org.bigbluebutton.conference.service.poll/poll/IPollRoomListener.java  $BBB/bigbluebutton-apps/src/main/java/org/bigbluebutton/conference/service/poll/IPollRoomListener.java
		cp   ./bbb-aps/src.main.java.org.bigbluebutton.conference.service.poll/poll/Poll.java  $BBB/bigbluebutton-apps/src/main/java/org/bigbluebutton/conference/service/poll/Poll.java
                  cp   ./bbb-aps/src.main.java.org.bigbluebutton.conference.service.poll/poll/PollApplication.java  $BBB/bigbluebutton-apps/src/main/java/org/bigbluebutton/conference/service/poll/PollApplication.java
		cp   ./bbb-aps/src.main.java.org.bigbluebutton.conference.service.poll/poll/PollHandler.java  $BBB/bigbluebutton-apps/src/main/java/org/bigbluebutton/conference/service/poll/PollHandler.java
		cp   ./bbb-aps/src.main.java.org.bigbluebutton.conference.service.poll/poll/PollRoom.java  $BBB/bigbluebutton-apps/src/main/java/org/bigbluebutton/conference/service/poll/PollRoom.java
		cp   ./bbb-aps/src.main.java.org.bigbluebutton.conference.service.poll/poll/PollRoomsManager.java  $BBB/bigbluebutton-apps/src/main/java/org/bigbluebutton/conference/service/poll/PollRoomsManager.java
		cp   ./bbb-aps/src.main.java.org.bigbluebutton.conference.service.poll/poll/PollService.java  $BBB/bigbluebutton-apps/src/main/java/org/bigbluebutton/conference/service/poll/PollService.java

               if [ -f  $BBB/bigbluebutton-apps/src/main/java/org/bigbluebutton/conference/service/poll/IPollRoomListener.java ] &&
		  [ -f 	$BBB/bigbluebutton-apps/src/main/java/org/bigbluebutton/conference/service/poll/Poll.java ] &&
		  [ -f  $BBB/bigbluebutton-apps/src/main/java/org/bigbluebutton/conference/service/poll/PollApplication.java ] &&
		  [ -f  $BBB/bigbluebutton-apps/src/main/java/org/bigbluebutton/conference/service/poll/PollHandler.java ] &&
		  [ -f  $BBB/bigbluebutton-apps/src/main/java/org/bigbluebutton/conference/service/poll/PollRoom.java ] &&
                  [ -f  $BBB/bigbluebutton-apps/src/main/java/org/bigbluebutton/conference/service/poll/PollRoomsManager.java ] &&
		  [ -f 	$BBB/bigbluebutton-apps/src/main/java/org/bigbluebutton/conference/service/poll/PollService.java ]
	            then 
			echo "                                                             [Done]"	
               fi
          else
          	   echo "Error Copying Server Side components. make sure you use 'sudo ./bbb-poll-install '"
         	   exit
	fi   

###############################################

	echo "Copying WEB-INF Dependencies...."
	cp   ./bbb-aps/src.main.webapps.WEB-INF/bbb-aps.xml $BBB/bigbluebutton-apps/src/main/webapp/WEB-INF/bbb-apps.xml
	cp   ./bbb-aps/src.main.webapps.WEB-INF/red5-web.xml  $BBB/bigbluebutton-apps/src/main/webapp/WEB-INF/red5-web.xml

 	if [ -f $BBB/bigbluebutton-apps/src/main/webapp/WEB-INF/bbb-apps.xml ] &&  [ -f  $BBB/bigbluebutton-apps/src/main/webapp/WEB-INF/red5-web.xml ]
         then
 		echo "                                                             [Done]"	
       fi
##################################################

	echo "Copying Client Side ....."
	echo " "
	mkdir -p $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling
	mkdir -p $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/events
        mkdir -p $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/managers 
        mkdir -p $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/maps
        mkdir -p $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/views
	mkdir -p $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/service
	mkdir -p $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/model

	if [ -d $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling ] &&
	   [ -d $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/events ] &&
	   [ -d $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/managers ] &&
	   [ -d $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/maps ] &&
           [ -d $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/views ] &&
           [ -d $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/model ]  		
 	 then
		echo "   ... Copying Managers..."
		cp     ./polling/managers/PollingWindowManager.as $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/managers/PollingWindowManager.as
		cp     ./polling/managers/PollingManager.as $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/managers/PollingManager.as  
		cp     ./polling/managers/ToolbarButtonManager.as $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/managers/ToolbarButtonManager.as

		  if [ -f $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/managers/PollingWindowManager.as ] &&
		     [ -f $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/managers/PollingManager.as  ] &&
		     [ -f  $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/managers/ToolbarButtonManager.as ]
			then 
	    		echo "                                                             [Done]"
		   else
			echo "Error copying managers.... "
			exit
		  fi

		  echo "   ... Copying Events... "
			cp     ./polling/events/ModuleEvent.as  $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/events/ModuleEvent.as
			cp     ./polling/events/OpenSavedPollEvent.as  $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/events/OpenSavedPollEvent.as	
			cp     ./polling/events/PollGetPollEvent.as  $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/events/PollGetPollEvent.as	
			cp     ./polling/events/PollGetStatusEvent.as  $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/events/PollGetStatusEvent.as
			cp     ./polling/events/PollGetTitlesEvent.as  $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/events/PollGetTitlesEvent.as
			cp     ./polling/events/PollingInstructionsWindowEvent.as  $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/events/PollingInstructionsWindowEvent.as
			cp     ./polling/events/PollingStatsWindowEvent.as  $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/events/PollingStatsWindowEvent.as
			cp     ./polling/events/PollingStatusCheckEvent.as  $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/events/PollingStatusCheckEvent.as
			cp     ./polling/events/PollingViewWindowEvent.as $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/events/PollingViewWindowEvent.as
			cp     ./polling/events/PollRefreshEvent.as $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/events/PollRefreshEvent.as
			cp     ./polling/events/PollReturnStatusEvent.as $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/events/PollReturnStatusEvent.as
			cp     ./polling/events/PollReturnTitlesEvent.as $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/events/PollReturnTitlesEvent.as
			cp     ./polling/events/PublishPollEvent.as $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/events/PublishPollEvent.as
			cp     ./polling/events/ReviewResultsEvent.as $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/events/ReviewResultsEvent.as
			cp     ./polling/events/SavePollEvent.as $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/events/SavePollEvent.as
			cp     ./polling/events/StartPollingEvent.as $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/events/StartPollingEvent.as
			cp     ./polling/events/StopPollEvent.as $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/events/StopPollEvent.as
			cp     ./polling/events/ToolbarComboEvent.as $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/events/ToolbarComboEvent.as
			cp     ./polling/events/VoteEvent.as $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/events/VoteEvent.as
			

			if [ -f $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/events/ModuleEvent.as ] &&
		           [ -f $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/events/OpenSavedPollEvent.as ] && 
		           [ -f $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/events/PollGetPollEvent.as ] && 
		           [ -f $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/events/PollGetStatusEvent.as ] && 
		           [ -f $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/events/PollGetTitlesEvent.as ] && 
		           [ -f $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/events/PollingInstructionsWindowEvent.as ] && 
		           [ -f $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/events/PollingStatsWindowEvent.as ] && 
		           [ -f $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/events/PollingStatusCheckEvent.as ] && 
		           [ -f $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/events/PollingViewWindowEvent.as ] && 
		           [ -f $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/events/PollRefreshEvent.as ] && 
		           [ -f $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/events/PollReturnStatusEvent.as ] && 
		           [ -f $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/events/PollReturnTitlesEvent.as ] && 
		           [ -f $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/events/ReviewResultsEvent.as ] && 
		           [ -f $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/events/StartPollingEvent.as ] && 
		           [ -f $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/events/StopPollEvent.as ] && 
		           [ -f $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/events/ToolbarComboEvent.as ] && 
		           [ -f $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/events/VoteEvent.as ] && 
		           [ -f $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/events/PublishPollEvent.as ] && 
		           [ -f $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/events/SavePollEvent.as ]  
			 	then 
	    		           echo "                                                             [Done]"
			else
				echo " Error occured copying polling/events"
				exit
			fi
					 
			
			echo "   ... Copying Views..."
			
			cp     ./polling/views/PollingInstructionsWindow.mxml $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/views/PollingInstructionsWindow.mxml
			cp     ./polling/views/PollingStatsWindow.mxml $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/views/PollingStatsWindow.mxml
			cp     ./polling/views/PollingViewWindow.mxml $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/views/PollingViewWindow.mxml
			cp     ./polling/views/PollingWindow.mxml $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/views/PollingWindow.mxml
			cp     ./polling/views/ToolbarButton.mxml $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/views/ToolbarButton.mxml
			cp     ./polling/views/ToolbarCombo.mxml $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/views/ToolbarCombo.mxml
 
		

		  	if [ -f $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/views/PollingInstructionsWindow.mxml ] &&
			   [ -f $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/views/PollingStatsWindow.mxml ] &&	
			   [ -f $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/views/PollingViewWindow.mxml ] &&	
			   [ -f $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/views/PollingWindow.mxml ] &&	
			   [ -f $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/views/ToolbarButton.mxml ] &&	
			   [ -f $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/views/ToolbarCombo.mxml ] 
			then
	    	        	echo "                                                             [Done]"

		        else
			   echo "Error copying Views.... "
			   exit

		        fi

			     echo "  ...Copying Maps, Models and Service .... "
			 cp     ./polling/maps/PollingEventMap.mxml $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/maps/PollingEventMap.mxml
			 cp     ./polling/service/PollingService.as $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/service/PollingService.as
			 cp     ./polling/model/PollObject.as $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/model/PollObject.as
			 cp     ./polling/model/ToolbarPollingRenderer.as $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/model/ToolbarPollingRenderer.as
			 cp     ./polling/model/ValueObject.as $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/model/ValueObject.as


			if [ -f  $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/maps/PollingEventMap.mxml ] &&
			   [ -f $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/service/PollingService.as ] &&
			   [ -f $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/model/PollObject.as ] &&
			   [ -f $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/model/ToolbarPollingRenderer.as ] &&
			   [ -f  $BBB/bigbluebutton-client/src/org/bigbluebutton/modules/polling/model/ValueObject.as ] 		
			
			    then
	    				echo "                                                             [Done]"
			else
				echo "Error copying Maps, Models and Service ... "	
				exit
			fi

			
   

		cp -R    ./PollingModule.mxml $BBB/bigbluebutton-client/src/
		echo "                                                             [Done]"	 
  	  else
        	echo "Error Copying Client side module.... "
        	exit  
	fi 
  

###################################################

	echo "Copying Client Side Dependencies ....."
	cp    ./polling_icon_dependencies/common.assets.images/poll_icon.png $BBB/bigbluebutton-client/src/org/bigbluebutton/common/assets/images/poll_icon.png
       	cp    ./polling_icon_dependencies/common.events/Images.as $BBB/bigbluebutton-client/src/org/bigbluebutton/common/events/Images.as
	 
	if [ -f $BBB/bigbluebutton-client/src/org/bigbluebutton/common/assets/images/poll_icon.png ] &&
	   [ -f $BBB/bigbluebutton-client/src/org/bigbluebutton/common/events/Images.as ]	
 	 then
           echo "                                                             [Done]" 
  	else
           echo "Error occured copying client side Dependencies"
	   exit
 	fi

##############################################

  ##  Locale list with translted polling module
	echo "Copying Locales..."
	cp    ./client.locale/en_US/bbbResources.properties  $BBB/bigbluebutton-client/locale/en_US/bbbResources.properties
	cp    ./client.locale/ru_RU/bbbResources.properties  $BBB/bigbluebutton-client/locale/ru_RU/bbbResources.properties
 	echo "                                                             [Done]"	

  	echo " Copying PollingModule.mxml "

	cp ./PollingModule.mxml  $BBB/bigbluebutton-client/src/PollingModule.mxml

 	if [ -f $BBB/bigbluebutton-client/src/PollingModule.mxml ]
	  then
 	echo "                                                             [Done]"
	else
		echo " Error copying PollingModule.mxml"
		exit
	fi	
##############################################


 ## IF YOU WANT TO TRY COMPILING EVERYTHING AT ONCE, UNCOMMENT THIS CODE!

  ## DOING ALL STEPS AT ONCE, COULD BE BAD IF ANY OF THE COMPILES FAILS!

	#echo "Recompiling bbb-client"

	#cd $BBB/bigbluebutton-client/
	#ant

	#echo "Compiling Polling Module"

 	#mxmlc  $BBB/bigbluebutton-client/src/PollingModule.mxml -sp $BBB/bigbluebutton-client/src  -l $BBB/bigbluebutton-client/libs -locale -accessible


	#if [ -f $BBB/bigbluebutton-client/src/PollingModule.swf ]
  	 #then
         #	 mv $BBB/bigbluebutton/bigbluebutton-client/src/PollingModule.swf $BBB/bigbluebutton-client/bin
         #       echo "                                                                [Done]"
  	 #else
         #	 echo "Polling Module is not compiled"
         #	 exit
	#fi

	#echo "Recompiling locales"
	#cd $BBB/bigbluebutton-client/
	#ant locales

	#echo "Stopping red5-server"
	#sudo /etc/init.d/red5 stop

	#echo "Recompiling bbb-aps"
	#cd $BBB/bigbluebutton-apps; gradle war deploy

	#echo "Starting red5-server"
	#cd /usr/share/red5/ 
	#sudo -u red5 ./red5.sh 

	#echo "Polling Installation completed"
else
  echo "ERROR: Cannot find your bigbluebutton directory, if it is not in  $BBB , please change the path in bbb-poll-install file. "
fi

echo " #####################################################################"

